/* soapPublicServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.45 for PublicService.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapPublicServiceSoapBindingProxy_H
#define soapPublicServiceSoapBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC PublicServiceSoapBindingProxy : public soap {
      public:
        /// Endpoint URL of service 'PublicServiceSoapBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in PublicService.h, if any
        /// Construct a proxy with new managing context
        PublicServiceSoapBindingProxy();
        /// Copy constructor
        PublicServiceSoapBindingProxy(const PublicServiceSoapBindingProxy& rhs);
        /// Construct proxy given a managing context
        PublicServiceSoapBindingProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        PublicServiceSoapBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        PublicServiceSoapBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        PublicServiceSoapBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        PublicServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~PublicServiceSoapBindingProxy();
        /// Initializer used by constructors
        virtual void PublicServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual PublicServiceSoapBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        PublicServiceSoapBindingProxy& operator=(const PublicServiceSoapBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'queryObjectInfo' (returns SOAP_OK or error code)
        virtual int queryObjectInfo(char *_senderID, char *_serviceID, char *_xmlSet, char *&_queryObjectInfoReturn)
        { return this->queryObjectInfo(NULL, NULL, _senderID, _serviceID, _xmlSet, _queryObjectInfoReturn); }
        virtual int queryObjectInfo(const char *soap_endpoint, const char *soap_action, char *_senderID, char *_serviceID, char *_xmlSet, char *&_queryObjectInfoReturn);
        /// Web service operation 'insertObjectInfo' (returns SOAP_OK or error code)
        virtual int insertObjectInfo(char *_senderID, char *_serviceID, char *_xmlSet, char *&_insertObjectInfoReturn)
        { return this->insertObjectInfo(NULL, NULL, _senderID, _serviceID, _xmlSet, _insertObjectInfoReturn); }
        virtual int insertObjectInfo(const char *soap_endpoint, const char *soap_action, char *_senderID, char *_serviceID, char *_xmlSet, char *&_insertObjectInfoReturn);
        /// Web service operation 'updateObjectInfo' (returns SOAP_OK or error code)
        virtual int updateObjectInfo(char *_senderID, char *_serviceID, char *_xmlSet, char *&_updateObjectInfoReturn)
        { return this->updateObjectInfo(NULL, NULL, _senderID, _serviceID, _xmlSet, _updateObjectInfoReturn); }
        virtual int updateObjectInfo(const char *soap_endpoint, const char *soap_action, char *_senderID, char *_serviceID, char *_xmlSet, char *&_updateObjectInfoReturn);
        /// Web service operation 'deleteObjectInfo' (returns SOAP_OK or error code)
        virtual int deleteObjectInfo(char *_senderID, char *_serviceID, char *_xmlSet, char *&_deleteObjectInfoReturn)
        { return this->deleteObjectInfo(NULL, NULL, _senderID, _serviceID, _xmlSet, _deleteObjectInfoReturn); }
        virtual int deleteObjectInfo(const char *soap_endpoint, const char *soap_action, char *_senderID, char *_serviceID, char *_xmlSet, char *&_deleteObjectInfoReturn);
        /// Web service operation 'callDataBaseProcess' (returns SOAP_OK or error code)
        virtual int callDataBaseProcess(char *_senderID, char *_serviceID, char *_xmlSet, char *&_callDataBaseProcessReturn)
        { return this->callDataBaseProcess(NULL, NULL, _senderID, _serviceID, _xmlSet, _callDataBaseProcessReturn); }
        virtual int callDataBaseProcess(const char *soap_endpoint, const char *soap_action, char *_senderID, char *_serviceID, char *_xmlSet, char *&_callDataBaseProcessReturn);
        /// Web service operation 'batchObjectInfo' (returns SOAP_OK or error code)
        virtual int batchObjectInfo(char *_senderID, char *_xmlSet, char *&_batchObjectInfoReturn)
        { return this->batchObjectInfo(NULL, NULL, _senderID, _xmlSet, _batchObjectInfoReturn); }
        virtual int batchObjectInfo(const char *soap_endpoint, const char *soap_action, char *_senderID, char *_xmlSet, char *&_batchObjectInfoReturn);
        /// Web service operation 'wsObjectInfo' (returns SOAP_OK or error code)
        virtual int wsObjectInfo(char *_senderID, char *_serviceID, char *_xmlSet, char *&_wsObjectInfoReturn)
        { return this->wsObjectInfo(NULL, NULL, _senderID, _serviceID, _xmlSet, _wsObjectInfoReturn); }
        virtual int wsObjectInfo(const char *soap_endpoint, const char *soap_action, char *_senderID, char *_serviceID, char *_xmlSet, char *&_wsObjectInfoReturn);
    };
#endif
